config/routes.rb
BbDev::Application.routes.draw do
  get "profiles/show"

  resources :babies

  devise_for :users

  get "home/index"
	
	root :to => "home#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/baby.rb
class Baby < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
	validates_format_of :name, with: /^[a-z0-9_]+$/, message: "must be lowercase alphanumerics only"
	validates_length_of :name, maximum: 32, message: "exceeds maximum of 32 characters"
	validates_exclusion_of :name, in: ['www', 'mail', 'ftp'], message: "is not available"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @babies }
    end
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
    @baby = Baby.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @baby }
    end
  end

  # GET /babies/new
  # GET /babies/new.json
  def new
    @baby = Baby.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @baby }
    end
  end

  # GET /babies/1/edit
  def edit
    @baby = Baby.find(params[:id])
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(params[:baby])

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render json: @baby, status: :created, location: @baby }
      else
        format.html { render action: "new" }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /babies/1
  # PUT /babies/1.json
  def update
    @baby = Baby.find(params[:id])

    respond_to do |format|
      if @baby.update_attributes(params[:baby])
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby = Baby.find(params[:id])
    @baby.destroy

    respond_to do |format|
      format.html { redirect_to babies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.first(conditions: { name: request.subdomain }) || not_found
  end

  def not_found
    raise ActionController::RoutingError.new('User Not Found')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	
def show
  @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/babies/_form.html.haml
= simple_form_for(@baby) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :city
    = f.input :state
    = f.input :sex
    = f.input :mother
    = f.input :father
    = f.input :birthday
    = f.input :word
    = f.input :walk
    = f.input :other

  .actions
    = f.button :submit

app/views/babies/edit.html.haml
%h1 Editing baby

= render 'form'

= link_to 'Show', @baby
\|
= link_to 'Back', babies_path

app/views/babies/index.html.haml
%h1 Listing babies

%table
  %tr
    %th Name
    %th City
    %th State
    %th Sex
    %th Mother
    %th Father
    %th Birthday
    %th Word
    %th Walk
    %th Other
    %th
    %th
    %th

  - @babies.each do |baby|
    %tr
      %td= baby.name
      %td= baby.city
      %td= baby.state
      %td= baby.sex
      %td= baby.mother
      %td= baby.father
      %td= baby.birthday
      %td= baby.word
      %td= baby.walk
      %td= baby.other
      %td= link_to 'Show', baby
      %td= link_to 'Edit', edit_baby_path(baby)
      %td= link_to 'Destroy', baby, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Baby', new_baby_path

app/views/babies/new.html.haml
%h1 New baby

= render 'form'

= link_to 'Back', babies_path

app/views/babies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @baby.name
%p
  %b City:
  = @baby.city
%p
  %b State:
  = @baby.state
%p
  %b Sex:
  = @baby.sex
%p
  %b Mother:
  = @baby.mother
%p
  %b Father:
  = @baby.father
%p
  %b Birthday:
  = @baby.birthday
%p
  %b Word:
  = @baby.word
%p
  %b Walk:
  = @baby.walk
%p
  %b Other:
  = @baby.other

= link_to 'Edit', edit_baby_path(@baby)
\|
= link_to 'Back', babies_path

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title BbDev
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		.navbar.navbar-fixed-top
			.navbar-inner
				.container
					%a.brand{:href => "/home"}
						Baby Brag
					.nav-collapse
						%ul.nav
							%li
								= active_link_to 'Home', '/'
							%li
								%a{:href => "/baby"} My Baby 
							%li.pull-right
								= render 'devise/menu/registration_items'
							%li
								= render 'devise/menu/login_items'
						%form.navbar-search.pull-right{:action => ""}
							%input.search-query.span2{:placeholder => "Search", :type => "text"}
		#main.container
			%p.notice-msg= notice
			%p.alert-msg= alert
			= yield

app/views/profiles/show.html.haml
%h1 Profile
%h4= @user.name
%h4= @user.email